/* AUTO-GENERATED by report/generateAreasJson.ts. Do not edit manually. */
const areasIndex = {
  areas: [
    'berlin-bezirke',
    'berlin-ortsteile',
    'berlin-plz',
    'brandenburg-berlin-plz',
    'brandenburg-gemeinden',
    'de-gemeinden',
    'de-laender',
    'de-landkreise',
    'de-regierungsbezirke',
    'de-staat',
    'de-verwaltungsgemeinschaften',
    'hamburg-bezirke',
  ],
  summaries: [
    {
      area: 'berlin-bezirke',
      displayName: 'Berlin Bezirke',
      matched: 12,
      officialOnly: 0,
      unmatchedOsm: 2,
    },
    {
      area: 'berlin-ortsteile',
      displayName: 'Berlin Ortsteile',
      matched: 0,
      officialOnly: 97,
      unmatchedOsm: 14,
    },
    {
      area: 'berlin-plz',
      displayName: 'Berlin PLZ',
      matched: 190,
      officialOnly: 3,
      unmatchedOsm: 0,
    },
    {
      area: 'brandenburg-berlin-plz',
      displayName: 'Brandenburg Berlin PLZ',
      matched: 405,
      officialOnly: 5,
      unmatchedOsm: 1,
    },
    {
      area: 'brandenburg-gemeinden',
      displayName: 'Brandenburg Gemeinden',
      matched: 409,
      officialOnly: 4,
      unmatchedOsm: 65,
    },
    {
      area: 'de-gemeinden',
      displayName: 'Deutschland Gemeinden',
      matched: 10499,
      officialOnly: 482,
      unmatchedOsm: 2003,
    },
    {
      area: 'de-laender',
      displayName: 'Deutschland Länder',
      matched: 16,
      officialOnly: 0,
      unmatchedOsm: 12486,
    },
    {
      area: 'de-landkreise',
      displayName: 'Deutschland Landkreise',
      matched: 400,
      officialOnly: 3,
      unmatchedOsm: 12102,
    },
    {
      area: 'de-regierungsbezirke',
      displayName: 'Deutschland Regierungsbezirke',
      matched: 19,
      officialOnly: 0,
      unmatchedOsm: 12483,
    },
    {
      area: 'de-staat',
      displayName: 'Deutschland Staat',
      matched: 1,
      officialOnly: 0,
      unmatchedOsm: 0,
    },
    {
      area: 'de-verwaltungsgemeinschaften',
      displayName: 'Deutschland Verwaltungsgemeinschaften',
      matched: 1291,
      officialOnly: 3308,
      unmatchedOsm: 11211,
    },
    {
      area: 'hamburg-bezirke',
      displayName: 'Hamburg Bezirke',
      matched: 0,
      officialOnly: 7,
      unmatchedOsm: 1,
    },
  ],
  geoDataSources: [
    {
      name: 'api.hamburg.de (regionalstatistische_daten_bezirke)',
      href: 'https://api.hamburg.de/datasets/v1/regionalstatistische_daten_bezirke/collections/regionalstatistische_daten_bezirke/items?f=json&filter=jahr%20%3D%20%272024%27&limit=20',
    },
    {
      name: 'BKG (VG25, vg25_gem)',
      href: 'https://daten.gdz.bkg.bund.de/produkte/vg/vg25_ebenen/aktuell/vg25.utm32s.gpkg.zip',
    },
    {
      name: 'BKG (VG25, vg25_krs)',
      href: 'https://daten.gdz.bkg.bund.de/produkte/vg/vg25_ebenen/aktuell/vg25.utm32s.gpkg.zip',
    },
    {
      name: 'BKG (VG25, vg25_lan)',
      href: 'https://daten.gdz.bkg.bund.de/produkte/vg/vg25_ebenen/aktuell/vg25.utm32s.gpkg.zip',
    },
    {
      name: 'BKG (VG25, vg25_rbz)',
      href: 'https://daten.gdz.bkg.bund.de/produkte/vg/vg25_ebenen/aktuell/vg25.utm32s.gpkg.zip',
    },
    {
      name: 'BKG (VG25, vg25_sta)',
      href: 'https://daten.gdz.bkg.bund.de/produkte/vg/vg25_ebenen/aktuell/vg25.utm32s.gpkg.zip',
    },
    {
      name: 'BKG (VG25, vg25_vwg)',
      href: 'https://daten.gdz.bkg.bund.de/produkte/vg/vg25_ebenen/aktuell/vg25.utm32s.gpkg.zip',
    },
    {
      name: 'gdi.berlin.de (alkis_bezirke:bezirksgrenzen)',
      href: 'https://gdi.berlin.de/services/wfs/alkis_bezirke?service=WFS&version=2.0.0&request=GetFeature&typeNames=alkis_bezirke%3Abezirksgrenzen&outputFormat=application%2Fjson&count=1000000&srsName=EPSG%3A4326',
    },
    {
      name: 'gdi.berlin.de (alkis_ortsteile:ortsteile)',
      href: 'https://gdi.berlin.de/services/wfs/alkis_ortsteile?service=WFS&version=2.0.0&request=GetFeature&typeNames=alkis_ortsteile%3Aortsteile&outputFormat=application%2Fjson&count=1000000&srsName=EPSG%3A4326',
    },
    {
      name: 'gdi.berlin.de (postleitzahlen:postleitzahlen)',
      href: 'https://gdi.berlin.de/services/wfs/postleitzahlen?service=WFS&version=2.0.0&request=GetFeature&typeNames=postleitzahlen%3Apostleitzahlen&outputFormat=application%2Fjson&srsName=EPSG%3A4326&count=1000000',
    },
    {
      name: 'isk.geobasis-bb.de (app:gem)',
      href: 'https://isk.geobasis-bb.de/ows/vg_wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&TYPENAMES=app%3Agem&outputFormat=application%2Fgml%2Bxml%3B%20version%3D3.2&srsName=urn%3Aogc%3Adef%3Acrs%3AEPSG%3A%3A4326',
    },
    {
      name: 'ogc-api.geobasis-bb.de (plz_bebb)',
      href: 'https://ogc-api.geobasis-bb.de/datasets/plz/collections/plz_bebb/items?bulk=true&f=json',
    },
    {
      name: 'OpenStreetMap (Geofabrik Germany extract) (germany-latest.osm.pbf)',
      href: 'https://download.geofabrik.de/europe/germany-latest.osm.pbf',
    },
  ],
  licenseSummaries: [
    {
      area: 'berlin-bezirke',
      displayName: 'Berlin Bezirke',
      officialLicenseLabel: 'DL-DE-ZERO-2.0',
      officialLicenseSourceUrl: 'https://www.govdata.de/dl-de/zero-2-0',
      officialOsmCompatibility: 'yes_waiver',
      officialOsmCompatibilitySourceUrl:
        'https://wiki.openstreetmap.org/w/images/3/34/2019-06-03_Datenlizenz_Deutschland_Berlin_OSM.pdf',
      officialOsmCompatibilityComment:
        'Berlin veroeffentlicht diese Datengrundlage unter DL-DE-ZERO-2.0 mit dokumentierter OSM-Freigabe.',
    },
    {
      area: 'berlin-ortsteile',
      displayName: 'Berlin Ortsteile',
      officialLicenseLabel: 'DL-DE-ZERO-2.0',
      officialLicenseSourceUrl: 'https://www.govdata.de/dl-de/zero-2-0',
      officialOsmCompatibility: 'yes_waiver',
      officialOsmCompatibilitySourceUrl:
        'https://wiki.openstreetmap.org/w/images/3/34/2019-06-03_Datenlizenz_Deutschland_Berlin_OSM.pdf',
      officialOsmCompatibilityComment:
        'Berlin veroeffentlicht diese Datengrundlage unter DL-DE-ZERO-2.0 mit dokumentierter OSM-Freigabe.',
    },
    {
      area: 'berlin-plz',
      displayName: 'Berlin PLZ',
      officialLicenseLabel: 'DL-DE-ZERO-2.0',
      officialLicenseSourceUrl: 'https://www.govdata.de/dl-de/zero-2-0',
      officialOsmCompatibility: 'yes_waiver',
      officialOsmCompatibilitySourceUrl:
        'https://wiki.openstreetmap.org/w/images/3/34/2019-06-03_Datenlizenz_Deutschland_Berlin_OSM.pdf',
      officialOsmCompatibilityComment:
        'Berlin veroeffentlicht diese Datengrundlage unter DL-DE-ZERO-2.0 mit dokumentierter OSM-Freigabe.',
    },
    {
      area: 'brandenburg-berlin-plz',
      displayName: 'Brandenburg Berlin PLZ',
      officialLicenseLabel: 'DL-DE-BY-2.0',
      officialLicenseSourceUrl: 'https://www.govdata.de/dl-de/by-2-0',
      officialOsmCompatibility: 'yes_waiver',
      officialOsmCompatibilitySourceUrl:
        'https://wiki.openstreetmap.org/wiki/Brandenburg/Geoportal#Rechtliche_Grundlagen',
      officialOsmCompatibilityComment:
        'Brandenburg-Daten mit dokumentierter OSM-Freigabe laut OSM-Wiki.',
    },
    {
      area: 'brandenburg-gemeinden',
      displayName: 'Brandenburg Gemeinden',
      officialLicenseLabel: 'DL-DE-BY-2.0',
      officialLicenseSourceUrl: 'https://www.govdata.de/dl-de/by-2-0',
      officialOsmCompatibility: 'yes_waiver',
      officialOsmCompatibilitySourceUrl:
        'https://wiki.openstreetmap.org/wiki/Brandenburg/Geoportal#Rechtliche_Grundlagen',
      officialOsmCompatibilityComment:
        'Brandenburg-Daten mit dokumentierter OSM-Freigabe laut OSM-Wiki.',
    },
    {
      area: 'de-gemeinden',
      displayName: 'Deutschland Gemeinden',
      officialLicenseLabel: 'DL-DE-BY-2.0',
      officialLicenseSourceUrl: 'https://www.govdata.de/dl-de/by-2-0',
      officialOsmCompatibility: 'unknown',
      officialOsmCompatibilitySourceUrl: 'https://www.govdata.de/dl-de/by-2-0',
      officialOsmCompatibilityComment:
        'Kompatibilitaet fuer OSM ist je Datensatz und Freigabekontext zu pruefen.',
    },
    {
      area: 'de-laender',
      displayName: 'Deutschland Länder',
      officialLicenseLabel: 'DL-DE-BY-2.0',
      officialLicenseSourceUrl: 'https://www.govdata.de/dl-de/by-2-0',
      officialOsmCompatibility: 'unknown',
      officialOsmCompatibilitySourceUrl: 'https://www.govdata.de/dl-de/by-2-0',
      officialOsmCompatibilityComment:
        'Kompatibilitaet fuer OSM ist je Datensatz und Freigabekontext zu pruefen.',
    },
    {
      area: 'de-landkreise',
      displayName: 'Deutschland Landkreise',
      officialLicenseLabel: 'DL-DE-BY-2.0',
      officialLicenseSourceUrl: 'https://www.govdata.de/dl-de/by-2-0',
      officialOsmCompatibility: 'unknown',
      officialOsmCompatibilitySourceUrl: 'https://www.govdata.de/dl-de/by-2-0',
      officialOsmCompatibilityComment:
        'Kompatibilitaet fuer OSM ist je Datensatz und Freigabekontext zu pruefen.',
    },
    {
      area: 'de-regierungsbezirke',
      displayName: 'Deutschland Regierungsbezirke',
      officialLicenseLabel: 'DL-DE-BY-2.0',
      officialLicenseSourceUrl: 'https://www.govdata.de/dl-de/by-2-0',
      officialOsmCompatibility: 'unknown',
      officialOsmCompatibilitySourceUrl: 'https://www.govdata.de/dl-de/by-2-0',
      officialOsmCompatibilityComment:
        'Kompatibilitaet fuer OSM ist je Datensatz und Freigabekontext zu pruefen.',
    },
    {
      area: 'de-staat',
      displayName: 'Deutschland Staat',
      officialLicenseLabel: 'DL-DE-BY-2.0',
      officialLicenseSourceUrl: 'https://www.govdata.de/dl-de/by-2-0',
      officialOsmCompatibility: 'unknown',
      officialOsmCompatibilitySourceUrl: 'https://www.govdata.de/dl-de/by-2-0',
      officialOsmCompatibilityComment:
        'Kompatibilitaet fuer OSM ist je Datensatz und Freigabekontext zu pruefen.',
    },
    {
      area: 'de-verwaltungsgemeinschaften',
      displayName: 'Deutschland Verwaltungsgemeinschaften',
      officialLicenseLabel: 'DL-DE-BY-2.0',
      officialLicenseSourceUrl: 'https://www.govdata.de/dl-de/by-2-0',
      officialOsmCompatibility: 'unknown',
      officialOsmCompatibilitySourceUrl: 'https://www.govdata.de/dl-de/by-2-0',
      officialOsmCompatibilityComment:
        'Kompatibilitaet fuer OSM ist je Datensatz und Freigabekontext zu pruefen.',
    },
    {
      area: 'hamburg-bezirke',
      displayName: 'Hamburg Bezirke',
      officialLicenseLabel: 'DL-DE-BY-2.0',
      officialLicenseSourceUrl: 'https://www.govdata.de/dl-de/by-2-0',
      officialOsmCompatibility: 'no',
      officialOsmCompatibilitySourceUrl:
        'https://api.hamburg.de/datasets/v1/regionalstatistische_daten_bezirke',
      officialOsmCompatibilityComment: 'Aktuell keine dokumentierte Zusatzfreigabe fuer OSM.',
    },
  ],
} as const

export default areasIndex
