/* AUTO-GENERATED by report/generateAreasJson.ts. Do not edit manually. */
const areasIndex = {
  areas: [
    'berlin-bezirke',
    'berlin-ortsteile',
    'berlin-plz',
    'brandenburg-berlin-plz',
    'brandenburg-gemeinden',
    'de-gemeinden',
    'de-laender',
    'de-landkreise',
    'de-regierungsbezirke',
    'de-staat',
    'de-verwaltungsgemeinschaften',
    'hamburg-bezirke',
  ],
  summaries: [
    {
      area: 'berlin-bezirke',
      displayName: 'Berlin Bezirke',
      matched: 12,
      officialOnly: 0,
      unmatchedOsm: 0,
    },
    {
      area: 'berlin-ortsteile',
      displayName: 'Berlin Ortsteile',
      matched: 97,
      officialOnly: 0,
      unmatchedOsm: 6,
    },
    {
      area: 'berlin-plz',
      displayName: 'Berlin PLZ',
      matched: 190,
      officialOnly: 3,
      unmatchedOsm: 0,
    },
    {
      area: 'brandenburg-berlin-plz',
      displayName: 'Brandenburg Berlin PLZ',
      matched: 405,
      officialOnly: 5,
      unmatchedOsm: 1,
    },
    {
      area: 'brandenburg-gemeinden',
      displayName: 'Brandenburg Gemeinden',
      matched: 409,
      officialOnly: 4,
      unmatchedOsm: 65,
    },
    {
      area: 'de-gemeinden',
      displayName: 'Deutschland Gemeinden',
      matched: 10499,
      officialOnly: 482,
      unmatchedOsm: 2003,
    },
    {
      area: 'de-laender',
      displayName: 'Deutschland Länder',
      matched: 16,
      officialOnly: 0,
      unmatchedOsm: 12486,
    },
    {
      area: 'de-landkreise',
      displayName: 'Deutschland Landkreise',
      matched: 400,
      officialOnly: 3,
      unmatchedOsm: 12102,
    },
    {
      area: 'de-regierungsbezirke',
      displayName: 'Deutschland Regierungsbezirke',
      matched: 19,
      officialOnly: 0,
      unmatchedOsm: 12483,
    },
    {
      area: 'de-staat',
      displayName: 'Deutschland Staat',
      matched: 1,
      officialOnly: 0,
      unmatchedOsm: 0,
    },
    {
      area: 'de-verwaltungsgemeinschaften',
      displayName: 'Deutschland Verwaltungsgemeinschaften',
      matched: 1291,
      officialOnly: 3308,
      unmatchedOsm: 11211,
    },
    {
      area: 'hamburg-bezirke',
      displayName: 'Hamburg Bezirke',
      matched: 0,
      officialOnly: 7,
      unmatchedOsm: 1,
    },
  ],
  geoDataSources: [
    {
      name: 'BKG (VG25, vg25_gem)',
      href: 'https://gdz.bkg.bund.de/index.php/default/digitale-geodaten/verwaltungsgebiete/verwaltungsgebiete-1-25-000-stand-31-12-vg25.html',
    },
    {
      name: 'BKG (VG25, vg25_krs)',
      href: 'https://gdz.bkg.bund.de/index.php/default/digitale-geodaten/verwaltungsgebiete/verwaltungsgebiete-1-25-000-stand-31-12-vg25.html',
    },
    {
      name: 'BKG (VG25, vg25_lan)',
      href: 'https://gdz.bkg.bund.de/index.php/default/digitale-geodaten/verwaltungsgebiete/verwaltungsgebiete-1-25-000-stand-31-12-vg25.html',
    },
    {
      name: 'BKG (VG25, vg25_rbz)',
      href: 'https://gdz.bkg.bund.de/index.php/default/digitale-geodaten/verwaltungsgebiete/verwaltungsgebiete-1-25-000-stand-31-12-vg25.html',
    },
    {
      name: 'BKG (VG25, vg25_sta)',
      href: 'https://gdz.bkg.bund.de/index.php/default/digitale-geodaten/verwaltungsgebiete/verwaltungsgebiete-1-25-000-stand-31-12-vg25.html',
    },
    {
      name: 'BKG (VG25, vg25_vwg)',
      href: 'https://gdz.bkg.bund.de/index.php/default/digitale-geodaten/verwaltungsgebiete/verwaltungsgebiete-1-25-000-stand-31-12-vg25.html',
    },
    {
      name: 'daten.berlin.de',
      href: 'https://daten.berlin.de/datensaetze/alkis-berlin-bezirke-wfs-ced31d7d',
    },
    {
      name: 'daten.berlin.de',
      href: 'https://daten.berlin.de/datensaetze/alkis-berlin-ortsteile-wfs-61bd3084',
    },
    {
      name: 'daten.berlin.de',
      href: 'https://daten.berlin.de/datensaetze/postleitzahlen-wfs-ac0f18fd',
    },
    {
      name: 'geoportal.brandenburg.de',
      href: 'https://geoportal.brandenburg.de/detailansichtdienst/render?view=gdibb&url=https%3A%2F%2Fgeoportal.brandenburg.de%2Fgs-json%2Fxml%3Ffileid%3Ded6ab7a1-7a64-4ceb-8d37-2e156b7f4546',
    },
    {
      name: 'geoportal.brandenburg.de',
      href: 'https://geoportal.brandenburg.de/detailansichtdienst/render?view=gdibb&url=https%3A%2F%2Fgeoportal.brandenburg.de%2Fgs-json%2Fxml%3Ffileid%3Db90acca9-e512-4c6c-a45e-ecc04a1e580c',
    },
    {
      name: 'suche.transparenz.hamburg.de',
      href: 'https://suche.transparenz.hamburg.de/dataset/regionalstatistische-daten-der-bezirke-hamburgs-und-hamburg-insgesamt17',
    },
  ],
  licenseSummaries: [
    {
      area: 'berlin-bezirke',
      displayName: 'Berlin Bezirke',
      officialLicenseLabel: 'DL-DE-ZERO-2.0',
      officialLicenseSourceUrl: 'https://www.govdata.de/dl-de/zero-2-0',
      officialOsmCompatibility: 'yes_waiver',
      officialOsmCompatibilitySourceUrl:
        'https://wiki.openstreetmap.org/w/images/3/34/2019-06-03_Datenlizenz_Deutschland_Berlin_OSM.pdf',
      officialOsmCompatibilityComment:
        'Berlin veroeffentlicht diese Datengrundlage unter DL-DE-ZERO-2.0 mit dokumentierter OSM-Freigabe.',
    },
    {
      area: 'berlin-ortsteile',
      displayName: 'Berlin Ortsteile',
      officialLicenseLabel: 'DL-DE-ZERO-2.0',
      officialLicenseSourceUrl: 'https://www.govdata.de/dl-de/zero-2-0',
      officialOsmCompatibility: 'yes_waiver',
      officialOsmCompatibilitySourceUrl:
        'https://wiki.openstreetmap.org/w/images/3/34/2019-06-03_Datenlizenz_Deutschland_Berlin_OSM.pdf',
      officialOsmCompatibilityComment:
        'Berlin veroeffentlicht diese Datengrundlage unter DL-DE-ZERO-2.0 mit dokumentierter OSM-Freigabe.',
    },
    {
      area: 'berlin-plz',
      displayName: 'Berlin PLZ',
      officialLicenseLabel: 'DL-DE-ZERO-2.0',
      officialLicenseSourceUrl: 'https://www.govdata.de/dl-de/zero-2-0',
      officialOsmCompatibility: 'yes_waiver',
      officialOsmCompatibilitySourceUrl:
        'https://wiki.openstreetmap.org/w/images/3/34/2019-06-03_Datenlizenz_Deutschland_Berlin_OSM.pdf',
      officialOsmCompatibilityComment:
        'Berlin veroeffentlicht diese Datengrundlage unter DL-DE-ZERO-2.0 mit dokumentierter OSM-Freigabe.',
    },
    {
      area: 'brandenburg-berlin-plz',
      displayName: 'Brandenburg Berlin PLZ',
      officialLicenseLabel: 'DL-DE-BY-2.0',
      officialLicenseSourceUrl: 'https://www.govdata.de/dl-de/by-2-0',
      officialOsmCompatibility: 'yes_waiver',
      officialOsmCompatibilitySourceUrl:
        'https://wiki.openstreetmap.org/wiki/Brandenburg/Geoportal#Rechtliche_Grundlagen',
      officialOsmCompatibilityComment:
        'Brandenburg-Daten mit dokumentierter OSM-Freigabe laut OSM-Wiki.',
    },
    {
      area: 'brandenburg-gemeinden',
      displayName: 'Brandenburg Gemeinden',
      officialLicenseLabel: 'DL-DE-BY-2.0',
      officialLicenseSourceUrl: 'https://www.govdata.de/dl-de/by-2-0',
      officialOsmCompatibility: 'yes_waiver',
      officialOsmCompatibilitySourceUrl:
        'https://wiki.openstreetmap.org/wiki/Brandenburg/Geoportal#Rechtliche_Grundlagen',
      officialOsmCompatibilityComment:
        'Brandenburg-Daten mit dokumentierter OSM-Freigabe laut OSM-Wiki.',
    },
    {
      area: 'de-gemeinden',
      displayName: 'Deutschland Gemeinden',
      officialLicenseLabel: 'CC-BY-4.0',
      officialLicenseSourceUrl: 'https://creativecommons.org/licenses/by/4.0/',
      officialOsmCompatibility: 'unknown',
      officialOsmCompatibilitySourceUrl: 'https://creativecommons.org/licenses/by/4.0/',
      officialOsmCompatibilityComment:
        'Kompatibilitaet fuer OSM ist je Datensatz und Freigabekontext zu pruefen.',
    },
    {
      area: 'de-laender',
      displayName: 'Deutschland Länder',
      officialLicenseLabel: 'CC-BY-4.0',
      officialLicenseSourceUrl: 'https://creativecommons.org/licenses/by/4.0/',
      officialOsmCompatibility: 'unknown',
      officialOsmCompatibilitySourceUrl: 'https://creativecommons.org/licenses/by/4.0/',
      officialOsmCompatibilityComment:
        'Kompatibilitaet fuer OSM ist je Datensatz und Freigabekontext zu pruefen.',
    },
    {
      area: 'de-landkreise',
      displayName: 'Deutschland Landkreise',
      officialLicenseLabel: 'CC-BY-4.0',
      officialLicenseSourceUrl: 'https://creativecommons.org/licenses/by/4.0/',
      officialOsmCompatibility: 'unknown',
      officialOsmCompatibilitySourceUrl: 'https://creativecommons.org/licenses/by/4.0/',
      officialOsmCompatibilityComment:
        'Kompatibilitaet fuer OSM ist je Datensatz und Freigabekontext zu pruefen.',
    },
    {
      area: 'de-regierungsbezirke',
      displayName: 'Deutschland Regierungsbezirke',
      officialLicenseLabel: 'CC-BY-4.0',
      officialLicenseSourceUrl: 'https://creativecommons.org/licenses/by/4.0/',
      officialOsmCompatibility: 'unknown',
      officialOsmCompatibilitySourceUrl: 'https://creativecommons.org/licenses/by/4.0/',
      officialOsmCompatibilityComment:
        'Kompatibilitaet fuer OSM ist je Datensatz und Freigabekontext zu pruefen.',
    },
    {
      area: 'de-staat',
      displayName: 'Deutschland Staat',
      officialLicenseLabel: 'CC-BY-4.0',
      officialLicenseSourceUrl: 'https://creativecommons.org/licenses/by/4.0/',
      officialOsmCompatibility: 'unknown',
      officialOsmCompatibilitySourceUrl: 'https://creativecommons.org/licenses/by/4.0/',
      officialOsmCompatibilityComment:
        'Kompatibilitaet fuer OSM ist je Datensatz und Freigabekontext zu pruefen.',
    },
    {
      area: 'de-verwaltungsgemeinschaften',
      displayName: 'Deutschland Verwaltungsgemeinschaften',
      officialLicenseLabel: 'CC-BY-4.0',
      officialLicenseSourceUrl: 'https://creativecommons.org/licenses/by/4.0/',
      officialOsmCompatibility: 'unknown',
      officialOsmCompatibilitySourceUrl: 'https://creativecommons.org/licenses/by/4.0/',
      officialOsmCompatibilityComment:
        'Kompatibilitaet fuer OSM ist je Datensatz und Freigabekontext zu pruefen.',
    },
    {
      area: 'hamburg-bezirke',
      displayName: 'Hamburg Bezirke',
      officialLicenseLabel: 'DL-DE-BY-2.0',
      officialLicenseSourceUrl: 'https://www.govdata.de/dl-de/by-2-0',
      officialOsmCompatibility: 'no',
      officialOsmCompatibilitySourceUrl:
        'https://api.hamburg.de/datasets/v1/regionalstatistische_daten_bezirke',
      officialOsmCompatibilityComment: 'Aktuell keine dokumentierte Zusatzfreigabe fuer OSM.',
    },
  ],
} as const

export default areasIndex
