import { DATASETS_DIRECTORY } from '../../../scripts/shared/datasetPaths.ts'
import type { ReportRow } from '../types/report'

/**
 * URLs match the repo layout at the site root: `/datasets/<area>/…`, `/__areas.json`.
 * Deploy: copy `report/dist/*`, repo `datasets/`, and repo `__areas.json` to the same origin (no `/repo-data` rewrite).
 */
/** Generated by `bun run generate-areas` (predev/prebuild); committed as repo-root `__areas.json`. */
export const areasIndexUrl = '/__areas.json'
export const processingStateUrl = '/data/processing-state.json'
export const processingLogJsonlUrl = '/data/processing-log.jsonl'

function datasetDataPath(area: string, rel: string): string {
  return `/${DATASETS_DIRECTORY}/${area}/${rel}`
}

export function comparisonTableJson(area: string, snapshot?: string | null) {
  if (snapshot) {
    return datasetDataPath(area, `history/comparison_table_${snapshot}.json`)
  }
  return datasetDataPath(area, 'output/comparison_table.json')
}

/** Path to PMTiles under the dev server (same origin). */
export function comparisonPmtilesPath(area: string, snapshot?: string | null) {
  if (snapshot) {
    return datasetDataPath(area, `history/comparison_${snapshot}.pmtiles`)
  }
  return datasetDataPath(area, 'output/comparison.pmtiles')
}

/** MapLibre vector source URL using the registered `pmtiles://` protocol. */
export function comparisonPmtilesMaplibreUrl(area: string, snapshot?: string | null): string {
  const path = comparisonPmtilesPath(area, snapshot)
  return `pmtiles://${window.location.origin}${path}`
}

/** Latest-only: `output/unmatched.pmtiles` (no historic per-snapshot file). */
export function comparisonUnmatchedPmtilesPath(area: string): string {
  return datasetDataPath(area, 'output/unmatched.pmtiles')
}

export function comparisonUnmatchedPmtilesMaplibreUrl(area: string): string {
  const path = comparisonUnmatchedPmtilesPath(area)
  return `pmtiles://${window.location.origin}${path}`
}

export function snapshotsUrl(area: string) {
  return datasetDataPath(area, 'snapshots.json')
}

/** Public path for official-for-edit GeoJSON (leading slash, under site root). */
export function officialForEditGeojsonHref(area: string, row: ReportRow): string | null {
  const rel = row.officialForEditPath
  if (rel == null || rel === '') return null
  return datasetDataPath(area, rel)
}
