import { spawnSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  listAreaLicenseSummaries,
  listComparisonAreaSummaries,
  listGeoDataSources,
} from './listComparisonAreas.ts'
import { resolveRuntimeRoot } from './runtimeDataRoot.ts'

function writeGeneratedModule(outPath: string, constName: string, payload: unknown): void {
  const body = JSON.stringify(payload, null, 2)
  const moduleSource = `/* AUTO-GENERATED by report/generateAreasJson.ts. Do not edit manually. */
const ${constName} = ${body} as const

export default ${constName}
`
  writeFileSync(outPath, moduleSource, 'utf8')
}

/** Writes generated runtime data modules consumed by report imports. */
const runtimeRoot = resolveRuntimeRoot()
const summaries = listComparisonAreaSummaries(runtimeRoot)
const areas = summaries.map((s) => s.area)
const geoDataSources = listGeoDataSources(runtimeRoot)
const licenseSummaries = listAreaLicenseSummaries(runtimeRoot)
const areasIndexOutPath = join(import.meta.dir, 'src', 'data', 'areasIndex.gen.ts')

writeGeneratedModule(areasIndexOutPath, 'areasIndex', {
  areas,
  summaries,
  geoDataSources,
  licenseSummaries,
})
const formatResult = spawnSync('bun', ['x', 'oxfmt', '--write', areasIndexOutPath], {
  stdio: 'inherit',
})

if (formatResult.status !== 0) {
  // Formatting failures should not block snapshot generation in CI.
  // The repository-level format/check step still enforces style separately.
  console.warn(
    `Warning: failed to format generated file (${areasIndexOutPath}), keeping source as-is.`,
  )
}

console.log(`Wrote ${areasIndexOutPath} (${areas.length} areas), DATA_ROOT=${runtimeRoot}`)
