import { spawnSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  listAreaLicenseSummaries,
  listComparisonAreaSummaries,
  listGeoDataSources,
} from './listComparisonAreas.ts'
import { resolveRuntimeRoot } from './runtimeDataRoot.ts'

/** Writes generated areas index module consumed by report runtime imports. */
const runtimeRoot = resolveRuntimeRoot()
const summaries = listComparisonAreaSummaries(runtimeRoot)
const areas = summaries.map((s) => s.area)
const geoDataSources = listGeoDataSources(runtimeRoot)
const licenseSummaries = listAreaLicenseSummaries(runtimeRoot)
const payload = JSON.stringify({ areas, summaries, geoDataSources, licenseSummaries }, null, 2)
const outPath = join(import.meta.dir, 'src', 'data', 'areasIndex.gen.ts')
const moduleSource = `/* AUTO-GENERATED by report/generateAreasJson.ts. Do not edit manually. */
const areasIndex = ${payload} as const

export default areasIndex
`

writeFileSync(outPath, moduleSource, 'utf8')
const formatResult = spawnSync('bun', ['x', 'oxfmt', '--write', outPath], {
  stdio: 'inherit',
})

if (formatResult.status !== 0) {
  throw new Error(`Failed to format ${outPath}`)
}

console.log(`Wrote ${outPath} (${areas.length} areas, DATA_ROOT=${runtimeRoot})`)
